if(NOT DEFINED INPUT_FILE OR NOT DEFINED OUTPUT_FILE OR NOT DEFINED VARIABLE_NAME)
    message(FATAL_ERROR "Usage: gen_bin_cpp.cmake must define INPUT_FILE OUTPUT_FILE VARIABLE_NAME")
endif()

file(READ ${INPUT_FILE} HEX_DATA HEX)
string(LENGTH ${HEX_DATA} HEX_LENGTH)
math(EXPR ARRAY_SIZE "${HEX_LENGTH} / 2")
set(CPP_CONTENT "// Auto Generate By gen_bin_cpp.cmake\n\n")

if(DEFINED VARIABLE_NAME_SPACE)
    string(APPEND CPP_CONTENT "namespace ${VARIABLE_NAME_SPACE}\n{\n\n")
endif()
string(APPEND CPP_CONTENT "unsigned char ${VARIABLE_NAME}[] = {\n")
set(COLUMN 0)
foreach(I RANGE 0 ${ARRAY_SIZE})
    math(EXPR INDEX "${I} * 2")
    if(${INDEX} LESS ${HEX_LENGTH})
        string(SUBSTRING ${HEX_DATA} ${INDEX} 2 HEX_BYTE)
        if(COLUMN EQUAL 0)
            string(APPEND CPP_CONTENT "  ")
        endif()
        string(APPEND CPP_CONTENT "0x${HEX_BYTE}, ")
        math(EXPR COLUMN "${COLUMN} + 1")
        if(COLUMN EQUAL 12)
            string(APPEND CPP_CONTENT "\n")
            set(COLUMN 0)
        endif()
    endif()
endforeach()
if(NOT COLUMN EQUAL 0)
    string(APPEND CPP_CONTENT "\n")
endif()
string(APPEND CPP_CONTENT "};\n\n")
string(APPEND CPP_CONTENT "unsigned int ${VARIABLE_NAME}_len = ${ARRAY_SIZE};\n")
if(DEFINED VARIABLE_NAME_SPACE)
    string(APPEND CPP_CONTENT "\n}\n")
endif()
file(WRITE ${OUTPUT_FILE} "${CPP_CONTENT}")